services:
  frontenddiet:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:81"
    environment:
      - NODE_ENV=production
      - VITE_projectIp=${VITE_projectIp}
    restart: unless-stopped
    volumes:
      - ./logs:/var/log/nginx
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
