services:
  frontdiet:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - VITE_projectIp=${VITE_projectIp}
    restart: unless-stopped
    volumes:
      - ./logs:/var/log/nginx
    networks:
      - diet-network

networks:
  diet-network:
    driver: bridge
